"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.compileArgumentFromDesc = exports.isArgumentDescPair = exports.isArgumentDescPositional = exports.isArgumentDescStandalone = exports.getArgumentDescType = exports.validateArgumentDescriptor = void 0;
var common_1 = require("@cmd-hub/common");
Object.defineProperty(exports, "validateArgumentDescriptor", { enumerable: true, get: function () { return common_1.validateArgumentDescriptor; } });
Object.defineProperty(exports, "getArgumentDescType", { enumerable: true, get: function () { return common_1.getArgumentDescType; } });
Object.defineProperty(exports, "isArgumentDescStandalone", { enumerable: true, get: function () { return common_1.isArgumentDescStandalone; } });
Object.defineProperty(exports, "isArgumentDescPositional", { enumerable: true, get: function () { return common_1.isArgumentDescPositional; } });
Object.defineProperty(exports, "isArgumentDescPair", { enumerable: true, get: function () { return common_1.isArgumentDescPair; } });
Object.defineProperty(exports, "compileArgumentFromDesc", { enumerable: true, get: function () { return common_1.compileArgumentFromDesc; } });
