"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deepMerge = exports.deepClone = exports.getInterfacePathsWithTypes = exports.getInterfacePaths = exports.isObject = exports.isObjectsEqual = exports.isEmpty = exports.removeFieldFromObject = exports.extractValueFromObject = exports.assignToCustomPath = void 0;
var extribute_1 = require("./extribute");
Object.defineProperty(exports, "assignToCustomPath", { enumerable: true, get: function () { return extribute_1.assignToCustomPath; } });
Object.defineProperty(exports, "extractValueFromObject", { enumerable: true, get: function () { return extribute_1.extractValueFromObject; } });
Object.defineProperty(exports, "removeFieldFromObject", { enumerable: true, get: function () { return extribute_1.removeFieldFromObject; } });
var check_1 = require("./check");
Object.defineProperty(exports, "isEmpty", { enumerable: true, get: function () { return check_1.isEmpty; } });
Object.defineProperty(exports, "isObjectsEqual", { enumerable: true, get: function () { return check_1.isObjectsEqual; } });
Object.defineProperty(exports, "isObject", { enumerable: true, get: function () { return check_1.isObject; } });
var path_creator_1 = require("./path-creator");
Object.defineProperty(exports, "getInterfacePaths", { enumerable: true, get: function () { return path_creator_1.getInterfacePaths; } });
Object.defineProperty(exports, "getInterfacePathsWithTypes", { enumerable: true, get: function () { return path_creator_1.getInterfacePathsWithTypes; } });
var clone_1 = require("./clone");
Object.defineProperty(exports, "deepClone", { enumerable: true, get: function () { return clone_1.deepClone; } });
var merge_1 = require("./merge");
Object.defineProperty(exports, "deepMerge", { enumerable: true, get: function () { return merge_1.deepMerge; } });
